"""inital db

Revision ID: 9e4c6062136a
Revises: 
Create Date: 2026-09-01 14:06:07.600634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e4c6062136a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('project_uuid', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('project_uuid')
    )
    op.create_table('chunks',
    sa.Column('chunk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_uuid', sa.UUID(), nullable=False),
    sa.Column('chunk_project_id', sa.String(), nullable=True),
    sa.Column('chunk_text', sa.String(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chunk_order', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['chunk_project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('chunk_id'),
    sa.UniqueConstraint('chunk_uuid')
    )
    op.create_index('ix_chunk_project_id', 'chunks', ['chunk_project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunk_project_id', table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('projects')
    # ### end Alembic commands ###
